### ISSUE TITLE
📊 Programming Languages

### ISSUE THREAD

**Issue by CSFelix** [CSFelix/data-science-studies#1]
# Programming Languages

* [x] Python
* [x] Julia
* [x] R
* [x] Streamlit

**Comment by Ramanna19** [comment]
Python

**Comment by CSFelix** [comment]
> Python

Actually, I'm gonna add the basic stuff on all these languages and after that I'll focus on deep stuff using Python.

This repo will be a better version of this one: [Deprecated Data Science Studies](https://github.com/Code-Plus-CUMI/deprecated-data-science-studies).

Feel free to check out the repo and tell your ideas about this topic!!

**Comment by CSFelix** [comment]
# Python

* [ ] Data Types, Variables, Constants, Inputs and Outputs
* [ ] Conditions, Loops and Exceptions
* [ ] Reading Files (CSV)
* [ ] Functions and Docstrings
* [ ] Objects

**Comment by CSFelix** [comment]
# R

* [ ] Data Types, Variables, Constants, Inputs and Outputs
* [ ] Conditions, Loops and Exceptions
* [ ] Reading Files (CSV)
* [ ] Functions and Docstrings
* [ ] Objects

**Comment by CSFelix** [comment]
# Julia

* [ ] Data Types, Variables, Constants, Inputs and Outputs
* [ ] Conditions, Loops and Exceptions
* [ ] Reading Files (CSV)
* [ ] Functions and Docstrings
* [ ] Objects

**Comment by CSFelix** [comment]
# Streamlit

* [ ]  the full folder
